apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  workspaces:
    - name: source
  steps:
    - name: build-image
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(workspaces.source.path)/Dockerfile
        - --context=$(workspaces.source.path)
        - --no-push
